In [12]:
import re
import os
import json
import time
import requests
import pandas as pd
from IPython.display import display

MAPBOX_TOKEN = 'pk.eyJ1IjoiaGJ1c2huZWxsIiwiYSI6ImNtbTNrYno0ZDAxb2UycXF6dTUwM3VyMmcifQ.jivZrXJ2wj5ml73B4BpPwg'
BATCH_URL = f"https://api.mapbox.com/search/geocode/v6/batch?access_token={MAPBOX_TOKEN}"

CHECKPOINT_FILE = 'geocoded_irish_properties.csv'
BATCH_SIZE = 1000

In [13]:
def prep_irish_address_for_mapbox(row, address_col='address', county_col='county'):
    if pd.isna(row[address_col]):
        return None
        
    address = str(row[address_col]).upper().strip()
    county = str(row[county_col]).upper().strip()

    # 1. Strip internal unit prefixes (APT, FLAT, UNIT, NO, NOS) and their numbers
    # because mapbox goes by building
    address = re.sub(r'^(?:APT|FLAT|UNIT|NO|NOS)\.?\s*\w+\s*-?\s*', '', address)
    
    # 2. Collapse explicit ranges (1-5, 1 TO 5, 1/2, 1 & 2) -> Keeps the first number
    # becayse mapbox only wants one number
    address = re.sub(r'\b(\d+[A-Z]*)\s*(?:-|TO|/|&|AND)\s*\d+[A-Z]*\b', r'\1', address)
    
    # 3. Collapse space-separated lists at the start (1 2 3 Corrib View -> 1 Corrib View)
    address = re.sub(r'^(\d+[A-Z]*)\s+\d+(?:\s+\d+)*\s+', r'\1 ', address)

    # 5. Clean up
    address = re.sub(r'\s{2,}', ' ', address)
    address = re.sub(r'^,\s*', '', address).strip()
    
    county = f"CO. {county}"

    # having county include CO. prefix will 
    if not address.endswith(county):
        address = f"{address}, {county}"
        
    return address

In [14]:
raw_df = pd.read_csv('../data/ppr-group-25200353-train-clean-final.csv')

print(f"loaded {len(raw_df)} records")

raw_df['mapbox_query'] = raw_df.apply(
    prep_irish_address_for_mapbox,
    axis=1, 
    address_col='address',
    county_col='county'
)

raw_df.head()

loaded 53992 records

,date_of_sale,address,county,price,not_full_market_price,vat_exclusive,property_description,mapbox_query
0,2016-02-29,"APT 14, RUSSELL COURT, FELTRIM RD",Dublin,118487.0,No,No,Second-Hand Dwelling house /Apartment,"RUSSELL COURT, FELTRIM RD, CO. DUBLIN"
1,2016-07-08,"19 PARK VILLAS, DEMESNE RD, DUNDALK",Louth,222000.0,No,No,Second-Hand Dwelling house /Apartment,"19 PARK VILLAS, DEMESNE RD, DUNDALK, CO. LOUTH"
2,2016-04-15,"No 2 The Grove, Cahereen Heights, Castleisland",Kerry,123348.0,No,Yes,New Dwelling house /Apartment,"THE GROVE, CAHEREEN HEIGHTS, CASTLEISLAND, CO...."
3,2016-12-21,"APT 4 BLOCK 6, WOODFORD, WHEATON HALL",Louth,115000.0,No,No,Second-Hand Dwelling house /Apartment,"BLOCK 6, WOODFORD, WHEATON HALL, CO. LOUTH"
4,2016-10-11,"18 GERALDINE ST, DUBLIN 7, DUBLIN",Dublin,225500.0,No,No,Second-Hand Dwelling house /Apartment,"18 GERALDINE ST, DUBLIN 7, DUBLIN, CO. DUBLIN"

In [4]:
if os.path.exists(CHECKPOINT_FILE):
    df = pd.read_csv(CHECKPOINT_FILE, low_memory=False)
    processed_count = df['confidence'].notna().sum()
    print(f"loaded checkpoint. {processed_count} addresses already processed")
else:
    df = raw_df.copy()
    df['latitude'] = pd.NA
    df['longitude'] = pd.NA
    df['confidence'] = pd.NA
    
    df.to_csv(CHECKPOINT_FILE, index=False)
    print("created new checkpoint file")

loaded checkpoint. 53992 addresses already processed

In [5]:
def run_geocoding_loop(df):
    while True:
        unprocessed = df[df['confidence'].isna()]
        
        if unprocessed.empty:
            print("all addresses processed")
            break
            
        batch_df = unprocessed.head(BATCH_SIZE)
        indices = batch_df.index.tolist()
        
        payload = [{"q": str(query), "country": "ie", "limit": 1} for query in batch_df['mapbox_query']]
        print(f"sending {BATCH_SIZE} addresses...")
        
        response = requests.post(BATCH_URL, json=payload)
        if response.status_code != 200:
            print(f"API Error {response.status_code}: {response.text}")
            break
            
        data = response.json()
        results_array = data.get('batch', data) if isinstance(data, dict) else data
        needs_review = False
        
        for i, res in enumerate(results_array):
            df_idx = indices[i]
            features = res.get('features', [])
            
            if features:
                feature = features[0]
                coords = feature['geometry']['coordinates']
                props = feature['properties']
                
                feature_type = props.get('feature_type', 'unknown')
                match_code_dict = props.get('match_code', {})
                
                conf = props.get('confidence')
                if not conf:
                    conf = match_code_dict.get('confidence', 'none')
                
                df.loc[df_idx, 'longitude'] = coords[0]
                df.loc[df_idx, 'confidence'] = coords[1]
                df.loc[df_idx, 'feature_type'] = feature_type
                df.loc[df_idx, 'confidence'] = conf
                df.loc[df_idx, 'match_code'] = json.dumps(match_code_dict)
                
            else:
                df.loc[df_idx, 'confidence'] = 'not_found'
                df.loc[df_idx, 'feature_type'] = 'not_found'
                needs_review = True
                
        df.to_csv(CHECKPOINT_FILE, index=False)
        
        if needs_review:
            print("mapbox cannot find address. review in next cell")
            break
        else:
            print("moving to next...")

run_geocoding_loop(df)

all addresses processed

In [6]:
from IPython.display import clear_output

failed_mask = df['confidence'] == 'not_found'
failed_indices = df[failed_mask].index

if len(failed_indices) == 0:
    print("no failed addresses to review")
else:
    print(f"found {len(failed_indices)} addresses that need manual entry\n")
    
    for idx in failed_indices:
        raw_address = df.loc[idx, 'address']
        query = df.loc[idx, 'mapbox_query']
        
        print(f"Row {idx} | Raw Address: {raw_address}")
        print(f"Mapbox Query: {query}")
        
        lat_input = input("Enter Latitude (or press Enter to skip & leave blank): ").strip()
            
        lon_input = input("Enter Longitude: ").strip()
        
        try:
            df.loc[idx, 'latitude'] = float(lat_input)
            df.loc[idx, 'longitude'] = float(lon_input)
            df.loc[idx, 'confidence'] = 'manual'
            df.loc[idx, 'feature_type'] = 'manual'
            df.loc[idx, 'match_code'] = '{"manual_override": true}'
            
            clear_output(wait=True)
            print(f"saved manual coordinates for row {idx}\n")
            
        except ValueError:
            clear_output(wait=True)
            print(f"invalid coordinate format. Skipped row {idx}\n")

    # Save your manual work immediately
    df.to_csv(CHECKPOINT_FILE, index=False)
    print("row saved")

no failed addresses to review

# Categorizing into Local Electoral Areas

In [39]:
import geopandas as gpd

lea_columns_to_keep = ['CSO_LEA', 'geometry']

gdf_lea = gpd.read_file('../data/cso_lea.geojson')[lea_columns_to_keep]

properties = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df['longitude'], df['latitude']),
    crs="EPSG:4326"
)

properties = properties.to_crs(gdf_lea.crs)

joined_data = gpd.sjoin(
    properties,
    gdf_lea,
    how="left",
    predicate="within"
)

joined_data.head()

,date_of_sale,address,county,price,not_full_market_price,vat_exclusive,property_description,mapbox_query,latitude,longitude,confidence,feature_type,match_code,geometry,index_right,CSO_LEA
0,2016-02-29,"APT 14, RUSSELL COURT, FELTRIM RD",Dublin,118487.0,No,No,Second-Hand Dwelling house /Apartment,"RUSSELL COURT, FELTRIM RD, CO. DUBLIN",53.433318,-6.177927,none,street,{},POINT (-6.17793 53.43332),86.0,HOWTH-MALAHIDE
1,2016-07-08,"19 PARK VILLAS, DEMESNE RD, DUNDALK",Louth,222000.0,No,No,Second-Hand Dwelling house /Apartment,"19 PARK VILLAS, DEMESNE RD, DUNDALK, CO. LOUTH",54.003768,-6.406065,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.40606 54.00377),66.0,DUNDALK-CARLINGFORD
2,2016-04-15,"No 2 The Grove, Cahereen Heights, Castleisland",Kerry,123348.0,No,Yes,New Dwelling house /Apartment,"THE GROVE, CAHEREEN HEIGHTS, CASTLEISLAND, CO....",52.221088,-9.468242,none,street,{},POINT (-9.46824 52.22109),43.0,CASTLEISLAND
3,2016-12-21,"APT 4 BLOCK 6, WOODFORD, WHEATON HALL",Louth,115000.0,No,No,Second-Hand Dwelling house /Apartment,"BLOCK 6, WOODFORD, WHEATON HALL, CO. LOUTH",53.050891,-8.399598,low,address,"{""address_number"": ""matched"", ""street"": ""unmat...",POINT (-8.3996 53.05089),109.0,LOUGHREA
4,2016-10-11,"18 GERALDINE ST, DUBLIN 7, DUBLIN",Dublin,225500.0,No,No,Second-Hand Dwelling house /Apartment,"18 GERALDINE ST, DUBLIN 7, DUBLIN, CO. DUBLIN",53.357662,-6.270328,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.27033 53.35766),30.0,CABRA-GLASNEVIN

In [40]:
# 1. Get the counts of sales for each LEA
lea_counts = joined_data['CSO_LEA'].value_counts()

# 2. Look at the top and bottom LEAs
print("Top 5 LEAs by number of sales:")
print(lea_counts.head())

print("\nBottom 5 LEAs by number of sales:")
print(lea_counts.tail())

# 3. Get the summary statistics
print("\nSummary of sales per LEA:")
print(lea_counts.describe())

Top 5 LEAs by number of sales:
CSO_LEA
HOWTH-MALAHIDE       1473
SWORDS                942
KILLINEY-SHANKILL     887
BALBRIGGAN            874
MIDLETON              812
Name: count, dtype: int64

Bottom 5 LEAs by number of sales:
CSO_LEA
CARNDONAGH    86
BELMULLET     82
MILFORD       70
MUINEBEAG     69
GRANARD       63
Name: count, dtype: int64

Summary of sales per LEA:
count     165.000000
mean      335.848485
std       197.944702
min        63.000000
25%       187.000000
50%       308.000000
75%       437.000000
max      1473.000000
Name: count, dtype: float64

In [41]:
joined_data = joined_data.rename(columns={
    'CSO_LEA': 'cso_lea',
})

In [42]:
joined_data.head()

,date_of_sale,address,county,price,not_full_market_price,vat_exclusive,property_description,mapbox_query,latitude,longitude,confidence,feature_type,match_code,geometry,index_right,cso_lea
0,2016-02-29,"APT 14, RUSSELL COURT, FELTRIM RD",Dublin,118487.0,No,No,Second-Hand Dwelling house /Apartment,"RUSSELL COURT, FELTRIM RD, CO. DUBLIN",53.433318,-6.177927,none,street,{},POINT (-6.17793 53.43332),86.0,HOWTH-MALAHIDE
1,2016-07-08,"19 PARK VILLAS, DEMESNE RD, DUNDALK",Louth,222000.0,No,No,Second-Hand Dwelling house /Apartment,"19 PARK VILLAS, DEMESNE RD, DUNDALK, CO. LOUTH",54.003768,-6.406065,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.40606 54.00377),66.0,DUNDALK-CARLINGFORD
2,2016-04-15,"No 2 The Grove, Cahereen Heights, Castleisland",Kerry,123348.0,No,Yes,New Dwelling house /Apartment,"THE GROVE, CAHEREEN HEIGHTS, CASTLEISLAND, CO....",52.221088,-9.468242,none,street,{},POINT (-9.46824 52.22109),43.0,CASTLEISLAND
3,2016-12-21,"APT 4 BLOCK 6, WOODFORD, WHEATON HALL",Louth,115000.0,No,No,Second-Hand Dwelling house /Apartment,"BLOCK 6, WOODFORD, WHEATON HALL, CO. LOUTH",53.050891,-8.399598,low,address,"{""address_number"": ""matched"", ""street"": ""unmat...",POINT (-8.3996 53.05089),109.0,LOUGHREA
4,2016-10-11,"18 GERALDINE ST, DUBLIN 7, DUBLIN",Dublin,225500.0,No,No,Second-Hand Dwelling house /Apartment,"18 GERALDINE ST, DUBLIN 7, DUBLIN, CO. DUBLIN",53.357662,-6.270328,high,address,"{""address_number"": ""matched"", ""street"": ""match...",POINT (-6.27033 53.35766),30.0,CABRA-GLASNEVIN

In [43]:
joined_data.to_csv('../data/ppr-group-25200353-train-geocoded.csv', index=False)